### ISSUE TITLE
编译的时候luci compat和luci base有冲突

### ISSUE THREAD

**Issue by xiaoluoabc123** [riverscn/easyiptv#1]

**Comment by riverscn** [comment]
luci base 是 luci compat 的依赖 https://github.com/openwrt/luci/blob/openwrt-19.07/modules/luci-compat/Makefile
不可能有冲突，请po出具体的报错

**Comment by xiaoluoabc123** [comment]
* check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/cbi/datatypes.lua
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/cbi.lua
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/model/firewall.lua
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/model/network/proto_ppp.lua
        But that file is already provided by package  * luci-proto-ppp
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/model/network.lua
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/browser.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/button.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/cell_valuefooter.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/cell_valueheader.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/compound.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/delegator.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/dvalue.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/dynlist.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/error.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/firewall_zonelist.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/footer.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/full_valuefooter.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/full_valueheader.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/fvalue.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/header.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/lvalue.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/map.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/mvalue.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/network_ifacelist.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/network_netinfo.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/network_netlist.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/nsection.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/nullsection.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/simpleform.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/tabcontainer.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/tblsection.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/tsection.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/tvalue.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/ucisection.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/upload.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/value.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/valuefooter.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/valueheader.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/wireless_modefreq.htm
        But that file is already provided by package  * luci-mod-admin-full
 * opkg_install_cmd: Cannot install package luci-app-iptvhelper.
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/cbi/datatypes.lua
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/cbi.lua
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/model/firewall.lua
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/model/network/proto_ppp.lua
        But that file is already provided by package  * luci-proto-ppp
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/model/network.lua
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/browser.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/button.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/cell_valuefooter.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/cell_valueheader.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/compound.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/delegator.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/dvalue.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/dynlist.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/error.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/firewall_zonelist.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/footer.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/full_valuefooter.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/full_valueheader.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/fvalue.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/header.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/lvalue.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/map.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/mvalue.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/network_ifacelist.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/network_netinfo.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/network_netlist.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/nsection.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/nullsection.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/simpleform.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/tabcontainer.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/tblsection.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/tsection.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/tvalue.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/ucisection.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/upload.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/value.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/valuefooter.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/valueheader.htm
        But that file is already provided by package  * luci-base
 * check_data_file_clashes: Package luci-compat wants to install file /workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/lua/luci/view/cbi/wireless_modefreq.htm
        But that file is already provided by package  * luci-mod-admin-full
 * opkg_install_cmd: Cannot install package luci-compat.
是这样的，您看看

**Comment by riverscn** [comment]
lean的源我没测试过。官方的openwrt没有这个问题。
你可以试试：
1. 先 make clean，再 make
2. 不行的话自己编辑makefile，把luci compat去掉（并且重新 make defconfig，或手动确保luci compat没有被勾选）。因为你已经有luci base了所以不写这个依赖应该没关系
