### ISSUE TITLE
长春电信的iptv似乎略有不同

### ISSUE THREAD

**Issue by VergilGao** [riverscn/easyiptv#10]
我最近成功在内网部署了iptv服务，但是在mwan3的配置里，我是很粗暴的将 10.0.0./8 全部走 iptv 来实现的
因为我发现，我在 iptv 口获取到的ip和我观看单播和回放实际访问的ip并不在同一个网段，因此我不知道该如何生成一个ipset，能最小化mwan3的路由，现在这个路由方式相当于完全放弃了一整个 10.0.0.0/8 段，

**Comment by VergilGao** [comment]
我看你的脚本也是只路由 iptv 机顶盒，或者说是指定mac地址的设备全部走iptv口，但是我想要每个设备都能看单播回放，同时能正常上网。

**Comment by lik2004k** [comment]
怎么玩啊，不知道怎么操作，想直接得到家里IPTV的列表

**Comment by VergilGao** [comment]
> 怎么玩啊，不知道怎么操作，想直接得到家里IPTV的列表

网上教程很多的，多搜多看。

**Comment by riverscn** [comment]
> 我最近成功在内网部署了iptv服务，但是在mwan3的配置里，我是很粗暴的将 10.0.0./8 全部走 iptv 来实现的 因为我发现，我在 iptv 口获取到的ip和我观看单播和回放实际访问的ip并不在同一个网段，因此我不知道该如何生成一个ipset，能最小化mwan3的路由，现在这个路由方式相当于完全放弃了一整个 10.0.0.0/8 段，

iptvhelper的主要功能之一就是侦听机顶盒的请求并记录ipset，然后你可以直接在mwan3之类的工具里调用这个自动生成的ipset

**Comment by riverscn** [comment]
> 我看你的脚本也是只路由 iptv 机顶盒，或者说是指定mac地址的设备全部走iptv口，但是我想要每个设备都能看单播回放，同时能正常上网。

组播转单播用udpxy，这样每个设备都能播放了

**Comment by VergilGao** [comment]
> > 我看你的脚本也是只路由 iptv 机顶盒，或者说是指定mac地址的设备全部走iptv口，但是我想要每个设备都能看单播回放，同时能正常上网。
> 
> 组播转单播用udpxy，这样每个设备都能播放了

我现在方案就是这样的，现在的问题是  rtsp 流
这个 rtsp 流我不知道他具体都要去哪个 ip 所以我就没办法给他设置规则，只能用 10.0.0.0/8 全部走 iptv 口这样的规则
我家本来内网 IP 是 10.99.16.0/20 段，现在被迫改到其他地址了。
