### ISSUE TITLE
一些北京联通IPTV的疑问

### ISSUE THREAD

**Issue by qwerttvv** [riverscn/easyiptv#2]
https://github.com/sdhzdmzzl/iptv_channel_scanner_windows
https://github.com/sdhzdmzzl/iptv_channel_scanner_linux

我抓包是239.3.1.x的，但是239.2.1.x也可以看，不知道你那儿咋样？

扫到的频道比在盒子抓包得到的列表多好多台

239.2.1.x比239.3.1.x多好多台，两者好多频道端口都不一样，而且后者更新频率好像慢

抓包里有个频道是“文化北京”，239.3.1.97:8001，这个台一直是循环播放一个视频

不知道你这里有没有别的有趣的发现……

**Comment by riverscn** [comment]
我发现了，是这样的。2.1好像是朝阳区的，3.1包含了昌平区之类的。可以扫描到CCTV5、6之类的机顶盒里没有的频道，还有付费频道也可以扫描到。
