### ISSUE TITLE
为什么编译出来不是中文？

### ISSUE THREAD

**Issue by superabbite1** [riverscn/easyiptv#4]
我看到有中文包的，为什么编译出来不是中文？

**Comment by riverscn** [comment]
如果你用的是lean的源而不是官方的最新版，把中文包源文件夹改名成 zh-cn。然后再把根文件夹改个名重新编译。

**Comment by superabbite1** [comment]
![QQ截图20210530004029](https://user-images.githubusercontent.com/79433125/120077981-b44b3600-c0df-11eb-99ab-193c2f3abe3d.png)
是这个文件夹改成zh-cn是吧，然后根文件夹是哪一个？

**Comment by superabbite1** [comment]
可以了，谢谢
